SHOPS = [
    "ALBERT",
    "BILLA",
    "D-VÝROBCI",
    "KAUFLAND",
    "MAKRO",
    "PENNY",
    "TESCO",
    "DD",
    "SP",
    "PBC",
    "SP MODLETICE",
    "NORMA",
    "JIP",
    "DM",
    "ROSSMANN",
    "LIDL",
    "COOP",
    "PB OSTATNÍ",
    "JINÉ",
]
# TODO: Add the ones that were added recently
ORGANIZATIONS = [
    "ADRA",
    "Armáda Spásy",
    "Bor",
    "CPPT",
    "DCHP",
    "DD Domino",
    "DIAKONIE",
    "DIAKONIE 2",
    "Domažlice",
    "Domovinka",
    "Domus",
    "František",
    "Horažďovice",
    "Jiné",
    "Jiné 2",
    "Jiné 3",
    "Jiné 4",
    "Klatovy",
    "Klokánek",
    "Koinonia",
    "Kotec ML",
    "Kotec TA",
    "Kralovice",
    "LC Dubeč",
    "LC Dubeč SP",
    "Ledovec",
    "Likvidace",
    "Máta",
    "Město Tachov",
    "Nadace 700",
    "Naděje",
    "ONŽ",
    "PBDŽ",
    "PBKV",
    "PONTON",
    "ProCit",
    "Rokycany",
    "SKP",
    "Spálené Poříčí",
    "Stříbro",
    "Sušice",
    "Tady a Teď",
    "TOTEM",
    "Trnová",
    "Ulice",
    "YMCA",
    "Zbiroh",
    "Zdislava",
    "ÚPS Třemošná",
    "ČFPB",
    "ČVT",
    "Žinkovy",
]
